/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CorrectChargeRequest } from '../../models/correct-charge-request';
import { ShipmentDto } from '../../models/shipment-dto';

export interface ApiV1AdminShippingShipmentsShipmentIdChargesTripPut$Params {
  shipmentId: string;
  trip: string;
      body: CorrectChargeRequest
}

export function apiV1AdminShippingShipmentsShipmentIdChargesTripPut(http: HttpClient, rootUrl: string, params: ApiV1AdminShippingShipmentsShipmentIdChargesTripPut$Params, context?: HttpContext): Observable<StrictHttpResponse<ShipmentDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/shipping/shipments/{shipmentId}/charges/{trip}', 'put');
  if (params) {
    rb.path('shipmentId', params.shipmentId, {});
    rb.path('trip', params.trip, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShipmentDto>;
    })
  );
}

