/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShipmentDto } from '../../models/shipment-dto';

export interface ApiV1AdminShippingOrdersOrderIdPartsPartIdReturnPickupPost$Params {
  orderId: string;
  partId: string;
}

export function apiV1AdminShippingOrdersOrderIdPartsPartIdReturnPickupPost(http: HttpClient, rootUrl: string, params: ApiV1AdminShippingOrdersOrderIdPartsPartIdReturnPickupPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ShipmentDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/shipping/orders/{orderId}/parts/{partId}/return-pickup', 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.path('partId', params.partId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShipmentDto>;
    })
  );
}

