/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedListOfShipmentDto } from '../../models/paged-list-of-shipment-dto';

export interface ApiV1AdminShippingShipmentsGet$Params {
  Page?: number;
  PageSize?: number;
  Status?: string;
  Search?: string;
}

export function apiV1AdminShippingShipmentsGet(http: HttpClient, rootUrl: string, params?: ApiV1AdminShippingShipmentsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedListOfShipmentDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminShippingShipmentsGet.PATH, 'get');
  if (params) {
    rb.query('Page', params.Page, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Status', params.Status, {});
    rb.query('Search', params.Search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedListOfShipmentDto>;
    })
  );
}

apiV1AdminShippingShipmentsGet.PATH = '/api/v1/admin/shipping/shipments';
