/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedListOfReviewDto } from '../../models/paged-list-of-review-dto';

export interface ApiV1SellerReviewsGet$Params {
  Page?: number;
  PageSize?: number;
  Unanswered?: boolean;
}

export function apiV1SellerReviewsGet(http: HttpClient, rootUrl: string, params?: ApiV1SellerReviewsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedListOfReviewDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/seller/reviews', 'get');
  if (params) {
    rb.query('Page', params.Page, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Unanswered', params.Unanswered, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedListOfReviewDto>;
    })
  );
}

