/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReviewDto } from '../../models/review-dto';
import { ReviewReplyRequest } from '../../models/review-reply-request';

export interface ApiV1SellerReviewsReviewIdReplyPut$Params {
  reviewId: string;
      body: ReviewReplyRequest
}

export function apiV1SellerReviewsReviewIdReplyPut(http: HttpClient, rootUrl: string, params: ApiV1SellerReviewsReviewIdReplyPut$Params, context?: HttpContext): Observable<StrictHttpResponse<ReviewDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1SellerReviewsReviewIdReplyPut.PATH, 'put');
  if (params) {
    rb.path('reviewId', params.reviewId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReviewDto>;
    })
  );
}

apiV1SellerReviewsReviewIdReplyPut.PATH = '/api/v1/seller/reviews/{reviewId}/reply';
