<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Asp.Versioning.Abstractions" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UPBazaar.SharedKernel\UPBazaar.SharedKernel.csproj" />
    <ProjectReference Include="..\UPBazaar.Infrastructure\UPBazaar.Infrastructure.csproj" />
    <ProjectReference Include="..\UPBazaar.Modules.Identity.Contracts\UPBazaar.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="..\UPBazaar.Modules.Catalog.Contracts\UPBazaar.Modules.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\UPBazaar.Modules.Inventory.Contracts\UPBazaar.Modules.Inventory.Contracts.csproj" />
    <ProjectReference Include="..\UPBazaar.Modules.Cart.Contracts\UPBazaar.Modules.Cart.Contracts.csproj" />
    <ProjectReference Include="..\UPBazaar.Modules.Orders.Contracts\UPBazaar.Modules.Orders.Contracts.csproj" />
    <ProjectReference Include="..\UPBazaar.Modules.Payments.Contracts\UPBazaar.Modules.Payments.Contracts.csproj" />
    <ProjectReference Include="..\UPBazaar.Modules.Shipping.Contracts\UPBazaar.Modules.Shipping.Contracts.csproj" />
    <ProjectReference Include="..\UPBazaar.Modules.Sellers.Contracts\UPBazaar.Modules.Sellers.Contracts.csproj" />
    <ProjectReference Include="..\UPBazaar.Modules.Settlements.Contracts\UPBazaar.Modules.Settlements.Contracts.csproj" />
    <ProjectReference Include="..\UPBazaar.Modules.Notifications.Contracts\UPBazaar.Modules.Notifications.Contracts.csproj" />
  </ItemGroup>

</Project>
