/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductDto } from '../../models/product-dto';
import { ProductPackageRequest } from '../../models/product-package-request';

export interface ApiV1AdminCatalogProductsProductIdPackagePut$Params {
  productId: string;
      body: ProductPackageRequest
}

export function apiV1AdminCatalogProductsProductIdPackagePut(http: HttpClient, rootUrl: string, params: ApiV1AdminCatalogProductsProductIdPackagePut$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminCatalogProductsProductIdPackagePut.PATH, 'put');
  if (params) {
    rb.path('productId', params.productId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductDto>;
    })
  );
}

apiV1AdminCatalogProductsProductIdPackagePut.PATH = '/api/v1/admin/catalog/products/{productId}/package';
