/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryDto } from '../../models/category-dto';
import { CategoryRequest } from '../../models/category-request';

export interface ApiV1AdminCatalogCategoriesCategoryIdPut$Params {
  categoryId: string;
      body: CategoryRequest
}

export function apiV1AdminCatalogCategoriesCategoryIdPut(http: HttpClient, rootUrl: string, params: ApiV1AdminCatalogCategoriesCategoryIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminCatalogCategoriesCategoryIdPut.PATH, 'put');
  if (params) {
    rb.path('categoryId', params.categoryId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoryDto>;
    })
  );
}

apiV1AdminCatalogCategoriesCategoryIdPut.PATH = '/api/v1/admin/catalog/categories/{categoryId}';
