/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductDto } from '../../models/product-dto';

export interface ApiV1AdminCatalogProductsProductIdSaleDelete$Params {
  productId: string;
}

export function apiV1AdminCatalogProductsProductIdSaleDelete(http: HttpClient, rootUrl: string, params: ApiV1AdminCatalogProductsProductIdSaleDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminCatalogProductsProductIdSaleDelete.PATH, 'delete');
  if (params) {
    rb.path('productId', params.productId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductDto>;
    })
  );
}

apiV1AdminCatalogProductsProductIdSaleDelete.PATH = '/api/v1/admin/catalog/products/{productId}/sale';
