/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedListOfAdminProductSummaryDto } from '../../models/paged-list-of-admin-product-summary-dto';

export interface ApiV1AdminCatalogProductsGet$Params {
  Page?: number;
  PageSize?: number;
  Search?: string;
  CategoryId?: string;
  Status?: string;
  SellerId?: string;
  OldestFirst?: boolean;
}

export function apiV1AdminCatalogProductsGet(http: HttpClient, rootUrl: string, params?: ApiV1AdminCatalogProductsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedListOfAdminProductSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/catalog/products', 'get');
  if (params) {
    rb.query('Page', params.Page, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Search', params.Search, {});
    rb.query('CategoryId', params.CategoryId, {});
    rb.query('Status', params.Status, {});
    rb.query('SellerId', params.SellerId, {});
    rb.query('OldestFirst', params.OldestFirst, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedListOfAdminProductSummaryDto>;
    })
  );
}

