/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedListOfPayoutSummaryDto } from '../../models/paged-list-of-payout-summary-dto';

export interface ApiV1SellerSettlementsPayoutsGet$Params {
  page?: number;
  pageSize?: number;
}

export function apiV1SellerSettlementsPayoutsGet(http: HttpClient, rootUrl: string, params?: ApiV1SellerSettlementsPayoutsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedListOfPayoutSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/seller/settlements/payouts', 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedListOfPayoutSummaryDto>;
    })
  );
}

