/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PayoutDto } from '../../models/payout-dto';

export interface ApiV1SellerSettlementsPayoutsPayoutIdGet$Params {
  payoutId: string;
}

export function apiV1SellerSettlementsPayoutsPayoutIdGet(http: HttpClient, rootUrl: string, params: ApiV1SellerSettlementsPayoutsPayoutIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PayoutDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/seller/settlements/payouts/{payoutId}', 'get');
  if (params) {
    rb.path('payoutId', params.payoutId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PayoutDto>;
    })
  );
}

