/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductReviewsDto } from '../../models/product-reviews-dto';

export interface ApiV1ReviewsProductsProductIdGet$Params {
  productId: string;
  page?: number;
  pageSize?: number;
}

export function apiV1ReviewsProductsProductIdGet(http: HttpClient, rootUrl: string, params: ApiV1ReviewsProductsProductIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductReviewsDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1ReviewsProductsProductIdGet.PATH, 'get');
  if (params) {
    rb.path('productId', params.productId, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductReviewsDto>;
    })
  );
}

apiV1ReviewsProductsProductIdGet.PATH = '/api/v1/reviews/products/{productId}';
