/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiV1ReviewsPhotosPhotoIdGet$Params {
  photoId: string;
  expires?: number;
  signature?: string;
}

export function apiV1ReviewsPhotosPhotoIdGet(http: HttpClient, rootUrl: string, params: ApiV1ReviewsPhotosPhotoIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/reviews/photos/{photoId}', 'get');
  if (params) {
    rb.path('photoId', params.photoId, {});
    rb.query('expires', params.expires, {});
    rb.query('signature', params.signature, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

