/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SellerMemberDto } from '../../models/seller-member-dto';
import { TeamRoleRequest } from '../../models/team-role-request';

export interface ApiV1SellersMeTeamMemberIdPut$Params {
  memberId: string;
      body: TeamRoleRequest
}

export function apiV1SellersMeTeamMemberIdPut(http: HttpClient, rootUrl: string, params: ApiV1SellersMeTeamMemberIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<SellerMemberDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1SellersMeTeamMemberIdPut.PATH, 'put');
  if (params) {
    rb.path('memberId', params.memberId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SellerMemberDto>;
    })
  );
}

apiV1SellersMeTeamMemberIdPut.PATH = '/api/v1/sellers/me/team/{memberId}';
