/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SellerMemberDto } from '../../models/seller-member-dto';

export interface ApiV1SellersMeTeamGet$Params {
}

export function apiV1SellersMeTeamGet(http: HttpClient, rootUrl: string, params?: ApiV1SellersMeTeamGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SellerMemberDto>>> {
  const rb = new RequestBuilder(rootUrl, apiV1SellersMeTeamGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SellerMemberDto>>;
    })
  );
}

apiV1SellersMeTeamGet.PATH = '/api/v1/sellers/me/team';
