/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SellerDto } from '../../models/seller-dto';
import { SellerProfileRequest } from '../../models/seller-profile-request';

export interface ApiV1SellersMeProfilePut$Params {
      body: SellerProfileRequest
}

export function apiV1SellersMeProfilePut(http: HttpClient, rootUrl: string, params: ApiV1SellersMeProfilePut$Params, context?: HttpContext): Observable<StrictHttpResponse<SellerDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1SellersMeProfilePut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SellerDto>;
    })
  );
}

apiV1SellersMeProfilePut.PATH = '/api/v1/sellers/me/profile';
