/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SellerAccessDto } from '../../models/seller-access-dto';

export interface ApiV1SellersMeAccessGet$Params {
}

export function apiV1SellersMeAccessGet(http: HttpClient, rootUrl: string, params?: ApiV1SellersMeAccessGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SellerAccessDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/sellers/me/access', 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SellerAccessDto>;
    })
  );
}

