/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SellerApplicationRequest } from '../../models/seller-application-request';
import { SellerDto } from '../../models/seller-dto';

export interface ApiV1SellersMeApplicationPost$Params {
      body: SellerApplicationRequest
}

export function apiV1SellersMeApplicationPost(http: HttpClient, rootUrl: string, params: ApiV1SellersMeApplicationPost$Params, context?: HttpContext): Observable<StrictHttpResponse<SellerDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/sellers/me/application', 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SellerDto>;
    })
  );
}

