/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CountStockRequest } from '../../models/count-stock-request';
import { StockLevelDto } from '../../models/stock-level-dto';

export interface ApiV1AdminInventoryStockProductIdPut$Params {
  productId: string;
      body: CountStockRequest
}

export function apiV1AdminInventoryStockProductIdPut(http: HttpClient, rootUrl: string, params: ApiV1AdminInventoryStockProductIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<StockLevelDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminInventoryStockProductIdPut.PATH, 'put');
  if (params) {
    rb.path('productId', params.productId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StockLevelDto>;
    })
  );
}

apiV1AdminInventoryStockProductIdPut.PATH = '/api/v1/admin/inventory/stock/{productId}';
