/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedListOfStockLevelDto } from '../../models/paged-list-of-stock-level-dto';

export interface ApiV1AdminInventoryStockGet$Params {
  page?: number;
  pageSize?: number;
  maxAvailable?: number;
}

export function apiV1AdminInventoryStockGet(http: HttpClient, rootUrl: string, params?: ApiV1AdminInventoryStockGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedListOfStockLevelDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminInventoryStockGet.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('maxAvailable', params.maxAvailable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedListOfStockLevelDto>;
    })
  );
}

apiV1AdminInventoryStockGet.PATH = '/api/v1/admin/inventory/stock';
