/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StockDetailDto } from '../../models/stock-detail-dto';

export interface ApiV1AdminInventoryStockProductIdGet$Params {
  productId: string;
}

export function apiV1AdminInventoryStockProductIdGet(http: HttpClient, rootUrl: string, params: ApiV1AdminInventoryStockProductIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<StockDetailDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/inventory/stock/{productId}', 'get');
  if (params) {
    rb.path('productId', params.productId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StockDetailDto>;
    })
  );
}

