/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthTokensDto } from '../../models/auth-tokens-dto';
import { VerifyTwoFactorRequest } from '../../models/verify-two-factor-request';

export interface ApiV1AuthVerify2FaPost$Params {
      body: VerifyTwoFactorRequest
}

export function apiV1AuthVerify2FaPost(http: HttpClient, rootUrl: string, params: ApiV1AuthVerify2FaPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthTokensDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AuthVerify2FaPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthTokensDto>;
    })
  );
}

apiV1AuthVerify2FaPost.PATH = '/api/v1/auth/verify-2fa';
