/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthTokensDto } from '../../models/auth-tokens-dto';
import { VerifyOtpRequest } from '../../models/verify-otp-request';

export interface ApiV1AuthVerifyOtpPost$Params {
      body: VerifyOtpRequest
}

export function apiV1AuthVerifyOtpPost(http: HttpClient, rootUrl: string, params: ApiV1AuthVerifyOtpPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthTokensDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/auth/verify-otp', 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthTokensDto>;
    })
  );
}

