/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PickupLocationDto } from '../../models/pickup-location-dto';
import { SellerPickupLocationRequest } from '../../models/seller-pickup-location-request';

export interface ApiV1SellerShippingPickupLocationPut$Params {
      body: SellerPickupLocationRequest
}

export function apiV1SellerShippingPickupLocationPut(http: HttpClient, rootUrl: string, params: ApiV1SellerShippingPickupLocationPut$Params, context?: HttpContext): Observable<StrictHttpResponse<PickupLocationDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/seller/shipping/pickup-location', 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PickupLocationDto>;
    })
  );
}

