/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PickupLocationDto } from '../../models/pickup-location-dto';

export interface ApiV1SellerShippingPickupLocationGet$Params {
}

export function apiV1SellerShippingPickupLocationGet(http: HttpClient, rootUrl: string, params?: ApiV1SellerShippingPickupLocationGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PickupLocationDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/seller/shipping/pickup-location', 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PickupLocationDto>;
    })
  );
}

