/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PackPartRequest } from '../../models/pack-part-request';
import { ShipmentDto } from '../../models/shipment-dto';

export interface ApiV1SellerShippingOrdersOrderIdPartsPartIdPackPost$Params {
  orderId: string;
  partId: string;
      body: PackPartRequest
}

export function apiV1SellerShippingOrdersOrderIdPartsPartIdPackPost(http: HttpClient, rootUrl: string, params: ApiV1SellerShippingOrdersOrderIdPartsPartIdPackPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ShipmentDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1SellerShippingOrdersOrderIdPartsPartIdPackPost.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.path('partId', params.partId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShipmentDto>;
    })
  );
}

apiV1SellerShippingOrdersOrderIdPartsPartIdPackPost.PATH = '/api/v1/seller/shipping/orders/{orderId}/parts/{partId}/pack';
