/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShipmentDto } from '../../models/shipment-dto';

export interface ApiV1SellerShippingOrdersOrderIdShipmentsGet$Params {
  orderId: string;
}

export function apiV1SellerShippingOrdersOrderIdShipmentsGet(http: HttpClient, rootUrl: string, params: ApiV1SellerShippingOrdersOrderIdShipmentsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShipmentDto>>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/seller/shipping/orders/{orderId}/shipments', 'get');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ShipmentDto>>;
    })
  );
}

