/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReviewDto } from '../../models/review-dto';

export interface ApiV1AdminReviewsReviewIdReplyHidePost$Params {
  reviewId: string;
}

export function apiV1AdminReviewsReviewIdReplyHidePost(http: HttpClient, rootUrl: string, params: ApiV1AdminReviewsReviewIdReplyHidePost$Params, context?: HttpContext): Observable<StrictHttpResponse<ReviewDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminReviewsReviewIdReplyHidePost.PATH, 'post');
  if (params) {
    rb.path('reviewId', params.reviewId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReviewDto>;
    })
  );
}

apiV1AdminReviewsReviewIdReplyHidePost.PATH = '/api/v1/admin/reviews/{reviewId}/reply/hide';
