/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RejectReviewRequest } from '../../models/reject-review-request';
import { ReviewDto } from '../../models/review-dto';

export interface ApiV1AdminReviewsReviewIdRejectPost$Params {
  reviewId: string;
      body: RejectReviewRequest
}

export function apiV1AdminReviewsReviewIdRejectPost(http: HttpClient, rootUrl: string, params: ApiV1AdminReviewsReviewIdRejectPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ReviewDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/reviews/{reviewId}/reject', 'post');
  if (params) {
    rb.path('reviewId', params.reviewId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReviewDto>;
    })
  );
}

