/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateStaffUserRequest } from '../../models/create-staff-user-request';
import { UserDto } from '../../models/user-dto';

export interface ApiV1AdminUsersPost$Params {
      body: CreateStaffUserRequest
}

export function apiV1AdminUsersPost(http: HttpClient, rootUrl: string, params: ApiV1AdminUsersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminUsersPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserDto>;
    })
  );
}

apiV1AdminUsersPost.PATH = '/api/v1/admin/users';
