/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignRolesRequest } from '../../models/assign-roles-request';
import { UserDto } from '../../models/user-dto';

export interface ApiV1AdminUsersUserIdRolesPut$Params {
  userId: string;
      body: AssignRolesRequest
}

export function apiV1AdminUsersUserIdRolesPut(http: HttpClient, rootUrl: string, params: ApiV1AdminUsersUserIdRolesPut$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/users/{userId}/roles', 'put');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserDto>;
    })
  );
}

