/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedListOfUserSummaryDto } from '../../models/paged-list-of-user-summary-dto';

export interface ApiV1AdminUsersGet$Params {
  Page?: number;
  PageSize?: number;
  Search?: string;
  UserType?: string;
}

export function apiV1AdminUsersGet(http: HttpClient, rootUrl: string, params?: ApiV1AdminUsersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedListOfUserSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminUsersGet.PATH, 'get');
  if (params) {
    rb.query('Page', params.Page, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Search', params.Search, {});
    rb.query('UserType', params.UserType, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedListOfUserSummaryDto>;
    })
  );
}

apiV1AdminUsersGet.PATH = '/api/v1/admin/users';
