import { Translation } from '@jsverse/transloco';
import { AppTranslations } from '@upbazaar/ui';
import en from './en.json';

/**
 * This app's strings. en.json and hi.json here are generated by `npm run i18n:split` from
 * libs/ui/src/lib/i18n, keeping only the keys this app uses: edit the shared files, never these.
 *
 * English is imported so it ships in the first download; Hindi loads when someone picks it.
 */
export const translations: AppTranslations = {
  en: () => Promise.resolve(en as Translation),
  hi: () => import('./hi.json').then((m) => m.default as Translation),
};
