/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeliveryChargeDto } from '../../models/delivery-charge-dto';

export interface ApiV1OrdersDeliveryChargeGet$Params {
}

export function apiV1OrdersDeliveryChargeGet(http: HttpClient, rootUrl: string, params?: ApiV1OrdersDeliveryChargeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DeliveryChargeDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1OrdersDeliveryChargeGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeliveryChargeDto>;
    })
  );
}

apiV1OrdersDeliveryChargeGet.PATH = '/api/v1/orders/delivery-charge';
