/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminProductSummaryDto {
  availableQuantity: number;
  categoryId: string;
  categoryName: string;
  currency: string;
  hasPackage: boolean;
  id: string;
  name: string;
  price: number;
  sellerId: string;
  sellerName: (string | null);
  sku: string;
  status: string;
  updatedAtUtc: string;
}
