/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CartLineDto } from '../models/cart-line-dto';
export interface CartDto {
  canCheckOut: boolean;
  currency: string;
  itemCount: number;
  lines: Array<CartLineDto>;
  subtotal: number;
}
