/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CartLineDto {
  availableQuantity: number;
  lineTotal: number;
  name: (string | null);
  priceWhenAdded: number;
  problem: (string | null);
  productId: string;
  quantity: number;
  sku: (string | null);
  unitPrice: number;
}
