/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CheckoutSessionDto {
  amountInPaise: number;
  currency: string;
  expiresAtUtc: string;
  gateway: string;
  gatewayOrderId: string;
  keyId: string;
  orderNumber: string;
  paymentId: string;
}
