/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CodRemittanceLineDto {
  amount: number;
  awb: string;
  matched: boolean;
  orderNumber: (string | null);
}
