/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CodSummaryDto {
  outstandingAmount: number;
  outstandingCount: number;
  overdueCount: number;
  overdueDays: number;
  shortCount: number;
}
