/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CodReceivableDto {
  awb: string;
  deliveredAtUtc: string;
  expected: number;
  id: string;
  isOverdue: boolean;
  orderId: string;
  orderNumber: string;
  orderPartId: string;
  received: number;
  sellerId: string;
  status: string;
  writeOffNote: (string | null);
}
