/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CodRemittanceLineDto } from '../models/cod-remittance-line-dto';
export interface CodRemittanceDto {
  fileName: string;
  id: string;
  lines: Array<CodRemittanceLineDto>;
  reference: string;
  remittedOn: string;
  total: number;
  unmatchedCount: number;
  uploadedAtUtc: string;
  uploadedBy: (string | null);
}
