/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CouponDto {
  code: string;
  description: string;
  discountType: string;
  endsAtUtc: (string | null);
  fundedBy: string;
  id: string;
  isActive: boolean;
  joined: boolean;
  maxDiscount: (number | null);
  minOrderValue: (number | null);
  perBuyerLimit: number;
  sellerId: (string | null);
  sellersJoined: number;
  startsAtUtc: string;
  totalLimit: (number | null);
  uses: number;
  value: number;
}
