/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateProductCommand {
  categoryId: string;
  currency: string;
  description: string | null;
  initialStock: number;
  name: string;
  price: number;
  sellerId: string;
  sku: string;
}
