/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateStaffUserRequest {
  displayName: string;
  email: string;
  password: string;
  preferredLanguage: (string | null);
  roles: (Array<string> | null);
}
