/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateProductRequest {
  brand: (string | null);
  categoryId: string;
  description: (string | null);
  name: string;
  onHandQuantity: (number | null);
  price: number;
  sellerId: string;
  sku: string;
}
