/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCouponRequest {
  code: string;
  description: string;
  discountType: string;
  endsAtUtc?: (string | null);
  fundedBy?: string;
  maxDiscount?: (number | null);
  minOrderValue?: (number | null);
  perBuyerLimit?: (number | null);
  startsAtUtc?: (string | null);
  totalLimit?: (number | null);
  value: number;
}
