/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeliveryAddressDto {
  city: string;
  district: (string | null);
  fullName: string;
  landmark: (string | null);
  line1: string;
  line2: (string | null);
  mobile: string;
  pincode: string;
  state: string;
}
