/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EarningDto {
  awaitingCash: boolean;
  commissionAmount: number;
  commissionPercent: number;
  currency: string;
  deliveredAtUtc: string;
  detail: (string | null);
  grossAmount: number;
  id: string;
  kind: string;
  netAmount: number;
  orderId: string;
  orderNumber: string;
  orderPartId: string;
  payableFromUtc: string;
  payoutId: (string | null);
  sellerId: string;
  status: string;
  tcsAmount: number;
  tdsAmount: number;
}
