/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReturnLineConditionDto } from '../models/return-line-condition-dto';
export interface InspectReturnRequest {
  condition: (string | null);
  lines?: Array<ReturnLineConditionDto>;
  note: (string | null);
}
