/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MergeCartLineRequest } from '../models/merge-cart-line-request';
export interface MergeCartRequest {
  lines: Array<MergeCartLineRequest>;
}
