/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One module and the SQL schema it owns.
 */
export interface ModuleInfo {

  /**
   * Module name.
   */
  name: string;

  /**
   * SQL schema owned by the module.
   */
  schema: string;
}
