/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewDto } from '../models/review-dto';
export interface MyReviewDto {
  canReview: boolean;
  maxPhotos: number;
  photosEnabled: boolean;
  productId: string;
  review: (null | ReviewDto);
}
