/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderLineDto } from '../models/order-line-dto';
import { ReturnRequestDto } from '../models/return-request-dto';
export interface OrderPartDto {
  cancellationReason: (string | null);
  deliveredAtUtc: (string | null);
  discount: number;
  id: string;
  lines: Array<OrderLineDto>;
  returnCondition: (string | null);
  returnRequest: (null | ReturnRequestDto);
  returnableUntilUtc: (string | null);
  sellerId: string;
  status: string;
  subtotal: number;
}
