/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderLineDto } from '../models/order-line-dto';
export interface OrderPartDto {
  cancellationReason: (string | null);
  id: string;
  lines: Array<OrderLineDto>;
  returnCondition: (string | null);
  sellerId: string;
  status: string;
  subtotal: number;
}
