/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderSummaryDto {
  amountPaid: (number | null);
  currency: string;
  id: string;
  itemCount: number;
  number: string;
  partStatuses: Array<string>;
  paymentMethod: string;
  paymentStatus: string;
  placedAtUtc: string;
  refundTotal: number;
  status: string;
  total: number;
}
