/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderLineDto } from '../models/order-line-dto';
export interface OrderDto {
  currency: string;
  customerId: string;
  gatewayOrderId: string | null;
  id: string;
  lines: Array<OrderLineDto>;
  orderNumber: string;
  paymentId: string | null;
  placedAtUtc: string;
  shippingFee: number;
  status: string;
  subtotal: number;
  total: number;
}
