/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderLineDto {
  discount?: number;
  lineTotal: number;
  name: string;
  productId: string;
  quantity: number;
  sku: string;
  unitPrice: number;
}
