/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeliveryAddressDto } from '../models/delivery-address-dto';
import { OrderPartDto } from '../models/order-part-dto';
export interface OrderDto {
  buyerId: string;
  canCancel: boolean;
  cancellationReason: (string | null);
  cancelledAtUtc: (string | null);
  couponCode: (string | null);
  currency: string;
  deliveryAddress: DeliveryAddressDto;
  discount: number;
  id: string;
  number: string;
  parts: Array<OrderPartDto>;
  paymentDueAtUtc: (string | null);
  paymentMethod: string;
  paymentReference: (string | null);
  paymentStatus: string;
  placedAtUtc: string;
  shippingFee: number;
  status: string;
  subtotal: number;
  total: number;
}
