/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderSummaryDto {
  currency: string;
  id: string;
  itemCount: number;
  number: string;
  paymentMethod: string;
  paymentStatus: string;
  placedAtUtc: string;
  status: string;
  total: number;
}
