/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RefundDto } from '../models/refund-dto';
export interface PagedListOfRefundDto {
  hasNextPage?: boolean;
  items: Array<RefundDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
