/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewDto } from '../models/review-dto';
export interface PagedListOfReviewDto {
  hasNextPage?: boolean;
  items: Array<ReviewDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
