/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CodRemittanceDto } from '../models/cod-remittance-dto';
export interface PagedListOfCodRemittanceDto {
  hasNextPage?: boolean;
  items: Array<CodRemittanceDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
