/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CodReceivableDto } from '../models/cod-receivable-dto';
export interface PagedListOfCodReceivableDto {
  hasNextPage?: boolean;
  items: Array<CodReceivableDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
