/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductSummaryDto } from '../models/product-summary-dto';
export interface PagedListOfProductSummaryDto {
  hasNextPage?: boolean;
  items: Array<ProductSummaryDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
