/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PayoutSummaryDto } from '../models/payout-summary-dto';
export interface PagedListOfPayoutSummaryDto {
  hasNextPage?: boolean;
  items: Array<PayoutSummaryDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
