/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentDto } from '../models/payment-dto';
export interface PagedListOfPaymentDto {
  hasNextPage?: boolean;
  items: Array<PaymentDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
