/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SellerOrderSummaryDto } from '../models/seller-order-summary-dto';
export interface PagedListOfSellerOrderSummaryDto {
  hasNextPage?: boolean;
  items: Array<SellerOrderSummaryDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
