/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminProductSummaryDto } from '../models/admin-product-summary-dto';
export interface PagedListOfAdminProductSummaryDto {
  hasNextPage?: boolean;
  items: Array<AdminProductSummaryDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
