/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StockLevelDto } from '../models/stock-level-dto';
export interface PagedListOfStockLevelDto {
  hasNextPage?: boolean;
  items: Array<StockLevelDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
