/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderSummaryDto } from '../models/order-summary-dto';
export interface PagedListOfOrderSummaryDto {
  hasNextPage?: boolean;
  items: Array<OrderSummaryDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
