/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReturnRequestSummaryDto } from '../models/return-request-summary-dto';
export interface PagedListOfReturnRequestSummaryDto {
  hasNextPage?: boolean;
  items: Array<ReturnRequestSummaryDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
