/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserSummaryDto } from '../models/user-summary-dto';
export interface PagedListOfUserSummaryDto {
  hasNextPage?: boolean;
  items: Array<UserSummaryDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
