/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ShipmentDto } from '../models/shipment-dto';
export interface PagedListOfShipmentDto {
  hasNextPage?: boolean;
  items: Array<ShipmentDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
