/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SellerSummaryDto } from '../models/seller-summary-dto';
export interface PagedListOfSellerSummaryDto {
  hasNextPage?: boolean;
  items: Array<SellerSummaryDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
