/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EarningDto } from '../models/earning-dto';
export interface PagedListOfEarningDto {
  hasNextPage?: boolean;
  items: Array<EarningDto>;
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages?: number;
}
