/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ParcelDto } from '../models/parcel-dto';
export interface ParcelSuggestionDto {
  missingSkus: Array<string>;
  parcel: (null | ParcelDto);
  pickupLocation: (string | null);
}
