/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentDto {
  amount: number;
  buyerId: string;
  createdAtUtc: string;
  currency: string;
  gateway: string;
  gatewayOrderId: string;
  gatewayPaymentId: (string | null);
  id: string;
  lastFailure: (string | null);
  orderId: string;
  orderNumber: string;
  orderOutcome: string;
  paidAtUtc: (string | null);
  refundDue: number;
  status: string;
}
