/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentDto {
  amount: number;
  capturedAtUtc: string | null;
  createdAtUtc: string;
  currency: string;
  gatewayOrderId: string;
  id: string;
  orderId: string;
  provider: string;
  status: string;
}
