/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PayoutSummaryDto {
  createdAtUtc: string;
  currency: string;
  earningCount: number;
  grossAmount: number;
  id: string;
  netAmount: number;
  paidAtUtc: (string | null);
  sellerId: string;
  shopName: string;
  status: string;
  utr: (string | null);
}
