/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EarningDto } from '../models/earning-dto';
export interface PayoutDto {
  accountHolder: string;
  accountNumber: string;
  commissionAmount: number;
  createdAtUtc: string;
  currency: string;
  earnings: Array<EarningDto>;
  grossAmount: number;
  id: string;
  ifsc: string;
  netAmount: number;
  paidAtUtc: (string | null);
  paidBy: (string | null);
  sellerId: string;
  shopName: string;
  status: string;
  tcsAmount: number;
  tdsAmount: number;
  utr: (string | null);
}
