/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PickupLocationDto {
  name: string;
  pincode: (string | null);
  sellerId: (string | null);
  updatedAtUtc: string;
}
