/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeliveryAddressDto } from '../models/delivery-address-dto';
export interface PlaceOrderRequest {
  deliveryAddress: DeliveryAddressDto;
  paymentMethod: string;
}
