/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductPackageRequest {
  breadthCm: (number | null);
  heightCm: (number | null);
  lengthCm: (number | null);
  weightGrams: (number | null);
}
