/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryDto } from '../models/category-dto';
export interface ProductDto {

  /**
   * Maker or seller brand as given on the listing.
   */
  brand?: (string | null);
  category: CategoryDto;
  createdAtUtc: string;
  currency: string;
  description: string | null;
  id: string;
  modifiedAtUtc: string | null;
  name: string;
  onHandQuantity: number;
  price: number;
  reservedQuantity: number;
  sellerId: string;
  sku: string;
  slug: string;
  status: string;
}
