/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicReviewDto } from '../models/public-review-dto';
import { RatingSummaryDto } from '../models/rating-summary-dto';
export interface ProductReviewsDto {
  items: Array<PublicReviewDto>;
  page: number;
  pageSize: number;
  productId: string;
  summary: RatingSummaryDto;
  totalCount: number;
}
