/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryDto } from '../models/category-dto';
import { ProductPackageDto } from '../models/product-package-dto';
import { ProductSaleDto } from '../models/product-sale-dto';
export interface ProductDto {
  brand: (string | null);
  category: CategoryDto;
  createdAtUtc: string;
  currency: string;
  currentPrice: number;
  description: (string | null);
  id: string;
  modifiedAtUtc: (string | null);
  name: string;
  onHandQuantity: number;
  package: (null | ProductPackageDto);
  price: number;
  reservedQuantity: number;
  reviewNote: (string | null);
  sale: (null | ProductSaleDto);
  sellerId: string;
  sku: string;
  slug: string;
  status: string;
}
