/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductSummaryDto {
  availableQuantity: number;
  currency: string;
  id: string;
  name: string;
  price: number;
  sku: string;
  status: string;
}
