/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewPhotoDto } from '../models/review-photo-dto';
import { ReviewReplyDto } from '../models/review-reply-dto';
export interface PublicReviewDto {
  body: (string | null);
  createdAtUtc: string;
  id: string;
  photos: Array<ReviewPhotoDto>;
  rating: number;
  reply: (null | ReviewReplyDto);
  reviewerName: string;
  title: (string | null);
}
