/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RefundDto {
  amount: number;
  createdAtUtc: string;
  gatewayRefundId: string;
  id: string;
  paymentId: string;
  status: string;
}
