/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RefundDto {
  amount: number;
  createdAtUtc: string;
  currency: string;
  gatewayPaymentId: (string | null);
  gatewayRefundId: (string | null);
  id: string;
  orderId: string;
  orderNumber: string;
  orderPartId: (string | null);
  paymentId: string;
  reason: string;
  refundedAtUtc: (string | null);
  refundedBy: (string | null);
  status: string;
}
