/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReturnItemDto } from '../models/return-item-dto';
export interface RequestReturnRequest {
  comment: (string | null);
  items?: Array<ReturnItemDto>;
  reason: string;
  refundUpiId: (string | null);
}
