/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReturnRequestDto {
  comment: (string | null);
  decidedAtUtc: (string | null);
  decisionNote: (string | null);
  reason: string;
  refundDue?: (number | null);
  refundUpiId: (string | null);
  requestedAtUtc: string;
  status: string;
}
