/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReturnRequestSummaryDto {
  comment: (string | null);
  currency: string;
  orderId: string;
  orderNumber: string;
  partId: string;
  partReturn?: string;
  partStatus: string;
  paymentMethod: string;
  reason: string;
  requestedAtUtc: string;
  sellerId: string;
  status: string;
  subtotal: number;
}
