/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewPhotoDto } from '../models/review-photo-dto';
import { ReviewReplyDto } from '../models/review-reply-dto';
export interface ReviewDto {
  body: (string | null);
  contentStatus: string;
  contentSubmittedAtUtc: (string | null);
  createdAtUtc: string;
  id: string;
  moderationNote: (string | null);
  photos: Array<ReviewPhotoDto>;
  productId: string;
  productName: string;
  rating: number;
  reply: (null | ReviewReplyDto);
  reviewerName: string;
  sellerId: string;
  title: (string | null);
}
