/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SellerAddressDto } from '../models/seller-address-dto';
import { SellerKycDto } from '../models/seller-kyc-dto';
export interface SellerDto {
  address: SellerAddressDto;
  contactEmail: (string | null);
  contactMobile: string;
  description: (string | null);
  id: string;
  kyc: SellerKycDto;
  ownerUserId: (string | null);
  reviewNote: (string | null);
  reviewedAtUtc: (string | null);
  shopName: string;
  status: string;
  submittedAtUtc: string;
}
