/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SellerKycDto {
  bankAccountHolder: string;
  bankAccountLast4: string;
  gstin: (string | null);
  ifsc: string;
  legalName: string;
  pan: string;
}
