/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SellerSummaryDto {
  contactMobile: string;
  id: string;
  ownerUserId: (string | null);
  shopName: string;
  status: string;
  submittedAtUtc: string;
}
