/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeliveryAddressDto } from '../models/delivery-address-dto';
import { OrderLineDto } from '../models/order-line-dto';
import { ReturnRequestDto } from '../models/return-request-dto';
export interface SellerOrderDto {
  cancellationReason: (string | null);
  codAmount: number;
  currency: string;
  deliveryAddress: DeliveryAddressDto;
  lines: Array<OrderLineDto>;
  orderId: string;
  orderNumber: string;
  partId: string;
  paymentMethod: string;
  placedAtUtc: string;
  returnCondition: (string | null);
  returnRequest: (null | ReturnRequestDto);
  status: string;
  subtotal: number;
}
