/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SellerAddressDto {
  city: string;
  line1: string;
  line2: (string | null);
  pincode: string;
  state: string;
}
