/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SellerProfileRequest {
  contactEmail: (string | null);
  contactMobile: string;
  description: (string | null);
  shopName: string;
}
