/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SellerApplicationRequest {
  addressLine1: string;
  addressLine2: (string | null);
  bankAccountHolder: string;
  bankAccountNumber: string;
  city: string;
  contactEmail: (string | null);
  contactMobile: string;
  description: (string | null);
  gstin: (string | null);
  ifsc: string;
  legalName: string;
  pan: string;
  pincode: string;
  shopName: string;
  state: string;
}
