/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SellerOrderSummaryDto {
  city: string;
  codAmount: number;
  currency: string;
  itemCount: number;
  orderId: string;
  orderNumber: string;
  partId: string;
  paymentMethod: string;
  placedAtUtc: string;
  returnRequestStatus: (string | null);
  status: string;
  subtotal: number;
}
