/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SellerMemberDto {
  addedAtUtc: string;
  displayName: string;
  email: (string | null);
  id: string;
  role: string;
  userId: string;
}
