/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SellerBalanceDto {
  accruingAmount: number;
  currency: string;
  onHoldAmount: number;
  paidAmount: number;
  payableAmount: number;
  pendingPayoutAmount: number;
}
