/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettlementPolicyDto {
  defaultCommissionPercent: number;
  modifiedAtUtc: (string | null);
  modifiedBy: (string | null);
  tcsPercent: number;
  tdsPercent: number;
}
