/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ParcelDto } from '../models/parcel-dto';
import { ShipmentChargeDto } from '../models/shipment-charge-dto';
import { ShipmentEventDto } from '../models/shipment-event-dto';
export interface ShipmentDto {
  awb: (string | null);
  carrier: string;
  carrierOrderId: (string | null);
  charges: Array<ShipmentChargeDto>;
  codAmount: number;
  courierName: (string | null);
  createdAtUtc: string;
  direction: string;
  events: Array<ShipmentEventDto>;
  id: string;
  lastError: (string | null);
  orderId: string;
  orderNumber: string;
  orderPartId: string;
  parcel: ParcelDto;
  paymentMode: string;
  pickupLocation: string;
  quoteError: (string | null);
  sellerId: string;
  status: string;
  trackingUrl: (string | null);
}
