/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShipmentChargeDto {
  amount: (number | null);
  charged: number;
  correctedAtUtc: (string | null);
  incurredAtUtc: (string | null);
  note: (string | null);
  trip: string;
}
