/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShipmentDto {
  awbNumber: string | null;
  courier: string | null;
  deliveredAtUtc: string | null;
  deliveryPostcode: string;
  expectedDeliveryUtc: string | null;
  id: string;
  orderId: string;
  orderNumber: string;
  status: string;
}
