/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StockMovementDto {
  id: string;
  occurredAtUtc: string;
  onHandAfter: number;
  onHandChange: number;
  reason: (string | null);
  recordedBy: (string | null);
  reference: (string | null);
  reservedChange: number;
  type: string;
}
