/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StockLevelDto } from '../models/stock-level-dto';
import { StockMovementDto } from '../models/stock-movement-dto';
export interface StockDetailDto {
  level: StockLevelDto;
  recentMovements: Array<StockMovementDto>;
}
