/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StockLevelDto {
  availableQuantity: number;
  onHandQuantity: number;
  productId: string;
  reservedQuantity: number;
}
