/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ModuleInfo } from '../models/module-info';

/**
 * What this build is and which modules it contains.
 */
export interface SystemInfoResponse {

  /**
   * Hosting environment name.
   */
  environment: string;

  /**
   * Modules composed into this host, with the schema each owns.
   */
  modules: Array<ModuleInfo>;

  /**
   * Informational assembly version.
   */
  version: string;
}
