/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProductRequest {
  brand: (string | null);
  categoryId: string;
  description: (string | null);
  name: string;
  price: number;
}
