/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  createdAtUtc: string;
  displayName: string;
  email: (string | null);
  emailVerified: boolean;
  id: string;
  mobile: (string | null);
  mobileVerified: boolean;
  permissions: Array<string>;
  preferredLanguage: string;
  roles: Array<string>;
  status: string;
  twoFactorEnabled: boolean;
  userType: string;
}
