/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserSummaryDto {
  createdAtUtc: string;
  displayName: string;
  email: (string | null);
  id: string;
  mobile: (string | null);
  roles: Array<string>;
  status: string;
  userType: string;
}
