/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RejectSellerRequest } from '../../models/reject-seller-request';
import { SellerDto } from '../../models/seller-dto';

export interface ApiV1AdminSellersSellerIdRejectPost$Params {
  sellerId: string;
      body: RejectSellerRequest
}

export function apiV1AdminSellersSellerIdRejectPost(http: HttpClient, rootUrl: string, params: ApiV1AdminSellersSellerIdRejectPost$Params, context?: HttpContext): Observable<StrictHttpResponse<SellerDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminSellersSellerIdRejectPost.PATH, 'post');
  if (params) {
    rb.path('sellerId', params.sellerId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SellerDto>;
    })
  );
}

apiV1AdminSellersSellerIdRejectPost.PATH = '/api/v1/admin/sellers/{sellerId}/reject';
