/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SellerDto } from '../../models/seller-dto';

export interface ApiV1AdminSellersSellerIdApprovePost$Params {
  sellerId: string;
}

export function apiV1AdminSellersSellerIdApprovePost(http: HttpClient, rootUrl: string, params: ApiV1AdminSellersSellerIdApprovePost$Params, context?: HttpContext): Observable<StrictHttpResponse<SellerDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/sellers/{sellerId}/approve', 'post');
  if (params) {
    rb.path('sellerId', params.sellerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SellerDto>;
    })
  );
}

