/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SellerOrderDto } from '../../models/seller-order-dto';

export interface ApiV1SellerOrdersOrderIdGet$Params {
  orderId: string;
}

export function apiV1SellerOrdersOrderIdGet(http: HttpClient, rootUrl: string, params: ApiV1SellerOrdersOrderIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SellerOrderDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1SellerOrdersOrderIdGet.PATH, 'get');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SellerOrderDto>;
    })
  );
}

apiV1SellerOrdersOrderIdGet.PATH = '/api/v1/seller/orders/{orderId}';
