/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CheckoutSessionDto } from '../../models/checkout-session-dto';

export interface ApiV1PaymentsOrdersOrderIdCheckoutPost$Params {
  orderId: string;
}

export function apiV1PaymentsOrdersOrderIdCheckoutPost(http: HttpClient, rootUrl: string, params: ApiV1PaymentsOrdersOrderIdCheckoutPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CheckoutSessionDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1PaymentsOrdersOrderIdCheckoutPost.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CheckoutSessionDto>;
    })
  );
}

apiV1PaymentsOrdersOrderIdCheckoutPost.PATH = '/api/v1/payments/orders/{orderId}/checkout';
