/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentResultDto } from '../../models/payment-result-dto';
import { VerifyRazorpayPaymentRequest } from '../../models/verify-razorpay-payment-request';

export interface ApiV1PaymentsRazorpayVerifyPost$Params {
      body: VerifyRazorpayPaymentRequest
}

export function apiV1PaymentsRazorpayVerifyPost(http: HttpClient, rootUrl: string, params: ApiV1PaymentsRazorpayVerifyPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentResultDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/payments/razorpay/verify', 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentResultDto>;
    })
  );
}

