/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RefundDto } from '../../models/refund-dto';
import { RefundRequest } from '../../models/refund-request';

export interface ApiPaymentsPaymentIdRefundsPost$Params {
  paymentId: string;
  'Idempotency-Key'?: string;
      body: RefundRequest
}

export function apiPaymentsPaymentIdRefundsPost(http: HttpClient, rootUrl: string, params: ApiPaymentsPaymentIdRefundsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<RefundDto>> {
  const rb = new RequestBuilder(rootUrl, apiPaymentsPaymentIdRefundsPost.PATH, 'post');
  if (params) {
    rb.path('paymentId', params.paymentId, {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RefundDto>;
    })
  );
}

apiPaymentsPaymentIdRefundsPost.PATH = '/api/payments/{paymentId}/refunds';
