/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentsConfigDto } from '../../models/payments-config-dto';

export interface ApiV1PaymentsConfigGet$Params {
}

export function apiV1PaymentsConfigGet(http: HttpClient, rootUrl: string, params?: ApiV1PaymentsConfigGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentsConfigDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/payments/config', 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentsConfigDto>;
    })
  );
}

