/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentDto } from '../../models/payment-dto';

export interface PaymentsGetPayment$Params {
  paymentId: string;
}

export function paymentsGetPayment(http: HttpClient, rootUrl: string, params: PaymentsGetPayment$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/payments/{paymentId}', 'get');
  if (params) {
    rb.path('paymentId', params.paymentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentDto>;
    })
  );
}

