/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CouponCodeRequest } from '../../models/coupon-code-request';
import { CouponPreviewDto } from '../../models/coupon-preview-dto';

export interface ApiV1PromotionsCouponsPreviewPost$Params {
      body: CouponCodeRequest
}

export function apiV1PromotionsCouponsPreviewPost(http: HttpClient, rootUrl: string, params: ApiV1PromotionsCouponsPreviewPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CouponPreviewDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/promotions/coupons/preview', 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CouponPreviewDto>;
    })
  );
}

