/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CouponDto } from '../../models/coupon-dto';

export interface ApiV1SellerPromotionsCampaignsGet$Params {
}

export function apiV1SellerPromotionsCampaignsGet(http: HttpClient, rootUrl: string, params?: ApiV1SellerPromotionsCampaignsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CouponDto>>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/seller/promotions/campaigns', 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CouponDto>>;
    })
  );
}

