/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CouponDto } from '../../models/coupon-dto';

export interface ApiV1SellerPromotionsCouponsCouponIdEndPost$Params {
  couponId: string;
}

export function apiV1SellerPromotionsCouponsCouponIdEndPost(http: HttpClient, rootUrl: string, params: ApiV1SellerPromotionsCouponsCouponIdEndPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CouponDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1SellerPromotionsCouponsCouponIdEndPost.PATH, 'post');
  if (params) {
    rb.path('couponId', params.couponId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CouponDto>;
    })
  );
}

apiV1SellerPromotionsCouponsCouponIdEndPost.PATH = '/api/v1/seller/promotions/coupons/{couponId}/end';
