/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CampaignJoinedRequest } from '../../models/campaign-joined-request';
import { CouponDto } from '../../models/coupon-dto';

export interface ApiV1SellerPromotionsCampaignsCouponIdJoinedPut$Params {
  couponId: string;
      body: CampaignJoinedRequest
}

export function apiV1SellerPromotionsCampaignsCouponIdJoinedPut(http: HttpClient, rootUrl: string, params: ApiV1SellerPromotionsCampaignsCouponIdJoinedPut$Params, context?: HttpContext): Observable<StrictHttpResponse<CouponDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/seller/promotions/campaigns/{couponId}/joined', 'put');
  if (params) {
    rb.path('couponId', params.couponId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CouponDto>;
    })
  );
}

