/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiV1ShippingWebhooksCourierTrackingPost$Params {
  'x-api-key'?: string;
}

export function apiV1ShippingWebhooksCourierTrackingPost(http: HttpClient, rootUrl: string, params?: ApiV1ShippingWebhooksCourierTrackingPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1ShippingWebhooksCourierTrackingPost.PATH, 'post');
  if (params) {
    rb.header('x-api-key', params['x-api-key'], {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1ShippingWebhooksCourierTrackingPost.PATH = '/api/v1/shipping/webhooks/courier-tracking';
