/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SystemInfoResponse } from '../../models/system-info-response';

export interface ApiV1SystemInfoGet$Params {
}

export function apiV1SystemInfoGet(http: HttpClient, rootUrl: string, params?: ApiV1SystemInfoGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SystemInfoResponse>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/system/info', 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SystemInfoResponse>;
    })
  );
}

