/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TotpSetupDto } from '../../models/totp-setup-dto';

export interface ApiV1UsersMe2FaSetupPost$Params {
}

export function apiV1UsersMe2FaSetupPost(http: HttpClient, rootUrl: string, params?: ApiV1UsersMe2FaSetupPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TotpSetupDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1UsersMe2FaSetupPost.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TotpSetupDto>;
    })
  );
}

apiV1UsersMe2FaSetupPost.PATH = '/api/v1/users/me/2fa/setup';
