/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MarkRefundedRequest } from '../../models/mark-refunded-request';
import { RefundDto } from '../../models/refund-dto';

export interface ApiV1AdminPaymentsRefundsRefundIdMarkRefundedPost$Params {
  refundId: string;
      body: MarkRefundedRequest
}

export function apiV1AdminPaymentsRefundsRefundIdMarkRefundedPost(http: HttpClient, rootUrl: string, params: ApiV1AdminPaymentsRefundsRefundIdMarkRefundedPost$Params, context?: HttpContext): Observable<StrictHttpResponse<RefundDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/payments/refunds/{refundId}/mark-refunded', 'post');
  if (params) {
    rb.path('refundId', params.refundId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RefundDto>;
    })
  );
}

