/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedListOfReturnRequestSummaryDto } from '../../models/paged-list-of-return-request-summary-dto';

export interface ApiV1AdminOrdersReturnsGet$Params {
  Page?: number;
  PageSize?: number;
  Status?: string;
}

export function apiV1AdminOrdersReturnsGet(http: HttpClient, rootUrl: string, params?: ApiV1AdminOrdersReturnsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedListOfReturnRequestSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminOrdersReturnsGet.PATH, 'get');
  if (params) {
    rb.query('Page', params.Page, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Status', params.Status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedListOfReturnRequestSummaryDto>;
    })
  );
}

apiV1AdminOrdersReturnsGet.PATH = '/api/v1/admin/orders/returns';
