/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CancelOrderRequest } from '../../models/cancel-order-request';
import { OrderDto } from '../../models/order-dto';

export interface ApiV1AdminOrdersOrderIdPartsPartIdCancelPost$Params {
  orderId: string;
  partId: string;
      body: CancelOrderRequest
}

export function apiV1AdminOrdersOrderIdPartsPartIdCancelPost(http: HttpClient, rootUrl: string, params: ApiV1AdminOrdersOrderIdPartsPartIdCancelPost$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/orders/{orderId}/parts/{partId}/cancel', 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.path('partId', params.partId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderDto>;
    })
  );
}

