/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReviewDto } from '../../models/review-dto';

export interface ApiV1ReviewsMineProductIdPhotosPhotoIdDelete$Params {
  productId: string;
  photoId: string;
}

export function apiV1ReviewsMineProductIdPhotosPhotoIdDelete(http: HttpClient, rootUrl: string, params: ApiV1ReviewsMineProductIdPhotosPhotoIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<ReviewDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/reviews/mine/{productId}/photos/{photoId}', 'delete');
  if (params) {
    rb.path('productId', params.productId, {});
    rb.path('photoId', params.photoId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReviewDto>;
    })
  );
}

