/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MyReviewDto } from '../../models/my-review-dto';

export interface ApiV1ReviewsMineProductIdGet$Params {
  productId: string;
}

export function apiV1ReviewsMineProductIdGet(http: HttpClient, rootUrl: string, params: ApiV1ReviewsMineProductIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MyReviewDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1ReviewsMineProductIdGet.PATH, 'get');
  if (params) {
    rb.path('productId', params.productId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MyReviewDto>;
    })
  );
}

apiV1ReviewsMineProductIdGet.PATH = '/api/v1/reviews/mine/{productId}';
