<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Asp.Versioning.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UPBazaar.SharedKernel\UPBazaar.SharedKernel.csproj" />
    <ProjectReference Include="..\UPBazaar.Infrastructure\UPBazaar.Infrastructure.csproj" />
    <ProjectReference Include="..\UPBazaar.Modules.Sellers.Contracts\UPBazaar.Modules.Sellers.Contracts.csproj" />
    <ProjectReference Include="..\UPBazaar.Modules.Identity.Contracts\UPBazaar.Modules.Identity.Contracts.csproj" />
  </ItemGroup>

</Project>
