/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartDto } from '../../models/cart-dto';
import { SetCartItemRequest } from '../../models/set-cart-item-request';

export interface ApiV1CartItemsProductIdPut$Params {
  productId: string;
      body: SetCartItemRequest
}

export function apiV1CartItemsProductIdPut(http: HttpClient, rootUrl: string, params: ApiV1CartItemsProductIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<CartDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1CartItemsProductIdPut.PATH, 'put');
  if (params) {
    rb.path('productId', params.productId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartDto>;
    })
  );
}

apiV1CartItemsProductIdPut.PATH = '/api/v1/cart/items/{productId}';
