/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartMergeResultDto } from '../../models/cart-merge-result-dto';
import { MergeCartRequest } from '../../models/merge-cart-request';

export interface ApiV1CartMergePost$Params {
      body: MergeCartRequest
}

export function apiV1CartMergePost(http: HttpClient, rootUrl: string, params: ApiV1CartMergePost$Params, context?: HttpContext): Observable<StrictHttpResponse<CartMergeResultDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1CartMergePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartMergeResultDto>;
    })
  );
}

apiV1CartMergePost.PATH = '/api/v1/cart/merge';
