/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartDto } from '../../models/cart-dto';

export interface ApiV1CartDelete$Params {
}

export function apiV1CartDelete(http: HttpClient, rootUrl: string, params?: ApiV1CartDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<CartDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/cart', 'delete');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartDto>;
    })
  );
}

