/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartDto } from '../../models/cart-dto';

export interface ApiV1CartItemsProductIdDelete$Params {
  productId: string;
}

export function apiV1CartItemsProductIdDelete(http: HttpClient, rootUrl: string, params: ApiV1CartItemsProductIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<CartDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1CartItemsProductIdDelete.PATH, 'delete');
  if (params) {
    rb.path('productId', params.productId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartDto>;
    })
  );
}

apiV1CartItemsProductIdDelete.PATH = '/api/v1/cart/items/{productId}';
