/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedListOfCodRemittanceDto } from '../../models/paged-list-of-cod-remittance-dto';

export interface ApiV1AdminShippingCodRemittancesGet$Params {
  page?: number;
  pageSize?: number;
}

export function apiV1AdminShippingCodRemittancesGet(http: HttpClient, rootUrl: string, params?: ApiV1AdminShippingCodRemittancesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedListOfCodRemittanceDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminShippingCodRemittancesGet.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedListOfCodRemittanceDto>;
    })
  );
}

apiV1AdminShippingCodRemittancesGet.PATH = '/api/v1/admin/shipping/cod/remittances';
