/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CodReceivableDto } from '../../models/cod-receivable-dto';
import { CodWriteOffRequest } from '../../models/cod-write-off-request';

export interface ApiV1AdminShippingCodReceivablesReceivableIdWriteOffPost$Params {
  receivableId: string;
      body: CodWriteOffRequest
}

export function apiV1AdminShippingCodReceivablesReceivableIdWriteOffPost(http: HttpClient, rootUrl: string, params: ApiV1AdminShippingCodReceivablesReceivableIdWriteOffPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CodReceivableDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminShippingCodReceivablesReceivableIdWriteOffPost.PATH, 'post');
  if (params) {
    rb.path('receivableId', params.receivableId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CodReceivableDto>;
    })
  );
}

apiV1AdminShippingCodReceivablesReceivableIdWriteOffPost.PATH = '/api/v1/admin/shipping/cod/receivables/{receivableId}/write-off';
