/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CodRemittanceDto } from '../../models/cod-remittance-dto';

export interface ApiV1AdminShippingCodRemittancesRemittanceIdGet$Params {
  remittanceId: string;
}

export function apiV1AdminShippingCodRemittancesRemittanceIdGet(http: HttpClient, rootUrl: string, params: ApiV1AdminShippingCodRemittancesRemittanceIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CodRemittanceDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminShippingCodRemittancesRemittanceIdGet.PATH, 'get');
  if (params) {
    rb.path('remittanceId', params.remittanceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CodRemittanceDto>;
    })
  );
}

apiV1AdminShippingCodRemittancesRemittanceIdGet.PATH = '/api/v1/admin/shipping/cod/remittances/{remittanceId}';
