/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedListOfCodReceivableDto } from '../../models/paged-list-of-cod-receivable-dto';

export interface ApiV1AdminShippingCodReceivablesGet$Params {
  filter?: string;
  page?: number;
  pageSize?: number;
}

export function apiV1AdminShippingCodReceivablesGet(http: HttpClient, rootUrl: string, params?: ApiV1AdminShippingCodReceivablesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedListOfCodReceivableDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/shipping/cod/receivables', 'get');
  if (params) {
    rb.query('filter', params.filter, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedListOfCodReceivableDto>;
    })
  );
}

