/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CodRemittanceDto } from '../../models/cod-remittance-dto';
import { IFormFile } from '../../models/i-form-file';

export interface ApiV1AdminShippingCodRemittancesPost$Params {
      body: {
'reference'?: string;
} & {
'remittedOn'?: string;
} & {
'file'?: IFormFile;
} & {
}
}

export function apiV1AdminShippingCodRemittancesPost(http: HttpClient, rootUrl: string, params: ApiV1AdminShippingCodRemittancesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CodRemittanceDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/shipping/cod/remittances', 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CodRemittanceDto>;
    })
  );
}

