/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CodSummaryDto } from '../../models/cod-summary-dto';

export interface ApiV1AdminShippingCodSummaryGet$Params {
}

export function apiV1AdminShippingCodSummaryGet(http: HttpClient, rootUrl: string, params?: ApiV1AdminShippingCodSummaryGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CodSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/shipping/cod/summary', 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CodSummaryDto>;
    })
  );
}

