/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CouponDto } from '../../models/coupon-dto';
import { CreateCouponRequest } from '../../models/create-coupon-request';

export interface ApiV1AdminPromotionsCouponsPost$Params {
      body: CreateCouponRequest
}

export function apiV1AdminPromotionsCouponsPost(http: HttpClient, rootUrl: string, params: ApiV1AdminPromotionsCouponsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CouponDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/promotions/coupons', 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CouponDto>;
    })
  );
}

