/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SellerCommissionDto } from '../../models/seller-commission-dto';

export interface ApiV1AdminSettlementsCommissionsGet$Params {
}

export function apiV1AdminSettlementsCommissionsGet(http: HttpClient, rootUrl: string, params?: ApiV1AdminSettlementsCommissionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SellerCommissionDto>>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminSettlementsCommissionsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SellerCommissionDto>>;
    })
  );
}

apiV1AdminSettlementsCommissionsGet.PATH = '/api/v1/admin/settlements/commissions';
