/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PayoutRunResultDto } from '../../models/payout-run-result-dto';

export interface ApiV1AdminSettlementsPayoutRunsPost$Params {
}

export function apiV1AdminSettlementsPayoutRunsPost(http: HttpClient, rootUrl: string, params?: ApiV1AdminSettlementsPayoutRunsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PayoutRunResultDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminSettlementsPayoutRunsPost.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PayoutRunResultDto>;
    })
  );
}

apiV1AdminSettlementsPayoutRunsPost.PATH = '/api/v1/admin/settlements/payout-runs';
