/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SellerCommissionDto } from '../../models/seller-commission-dto';
import { SellerCommissionRequest } from '../../models/seller-commission-request';

export interface ApiV1AdminSettlementsCommissionsSellerIdPut$Params {
  sellerId: string;
      body: SellerCommissionRequest
}

export function apiV1AdminSettlementsCommissionsSellerIdPut(http: HttpClient, rootUrl: string, params: ApiV1AdminSettlementsCommissionsSellerIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<SellerCommissionDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminSettlementsCommissionsSellerIdPut.PATH, 'put');
  if (params) {
    rb.path('sellerId', params.sellerId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SellerCommissionDto>;
    })
  );
}

apiV1AdminSettlementsCommissionsSellerIdPut.PATH = '/api/v1/admin/settlements/commissions/{sellerId}';
