/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SellerNameDto } from '../../models/seller-name-dto';

export interface ApiV1AdminSettlementsSellersGet$Params {
}

export function apiV1AdminSettlementsSellersGet(http: HttpClient, rootUrl: string, params?: ApiV1AdminSettlementsSellersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SellerNameDto>>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminSettlementsSellersGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SellerNameDto>>;
    })
  );
}

apiV1AdminSettlementsSellersGet.PATH = '/api/v1/admin/settlements/sellers';
