/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettlementPolicyDto } from '../../models/settlement-policy-dto';
import { SettlementPolicyRequest } from '../../models/settlement-policy-request';

export interface ApiV1AdminSettlementsPolicyPut$Params {
      body: SettlementPolicyRequest
}

export function apiV1AdminSettlementsPolicyPut(http: HttpClient, rootUrl: string, params: ApiV1AdminSettlementsPolicyPut$Params, context?: HttpContext): Observable<StrictHttpResponse<SettlementPolicyDto>> {
  const rb = new RequestBuilder(rootUrl, '/api/v1/admin/settlements/policy', 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettlementPolicyDto>;
    })
  );
}

