/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedListOfPayoutSummaryDto } from '../../models/paged-list-of-payout-summary-dto';

export interface ApiV1AdminSettlementsPayoutsGet$Params {
  Page?: number;
  PageSize?: number;
  Status?: string;
  SellerId?: string;
}

export function apiV1AdminSettlementsPayoutsGet(http: HttpClient, rootUrl: string, params?: ApiV1AdminSettlementsPayoutsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedListOfPayoutSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdminSettlementsPayoutsGet.PATH, 'get');
  if (params) {
    rb.query('Page', params.Page, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Status', params.Status, {});
    rb.query('SellerId', params.SellerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedListOfPayoutSummaryDto>;
    })
  );
}

apiV1AdminSettlementsPayoutsGet.PATH = '/api/v1/admin/settlements/payouts';
